pipeline:
  install:
    image: node:latest
    pull: true
    commands:
      - node -v
      - npm -v
      - npm install
  test: 
   image: node:latest
   commands:
      - npm run test
  build:
    image: node:latest
    commands:
      - npm run build
      - ls dist
  deploy-production:
    image: plugins/s3-sync:1
    pull: true
    secrets: [aws_access_key_id, aws_secret_access_key]
    bucket: london-rpg.com
    source: ./public
    region: eu-west-2
    when:
      event: push
      branch: master
